### ISSUE TITLE
phone number format too rigid, creates errors

### ISSUE THREAD

**Issue by nurunecohack** [filamentgroup/politespace#38]
Based on the demo, this can't be used on phone numbers: in very common use cases, it converts valid entered data into invalid data.

"1234567890" is converted to "123-456-7890" = OK
"(123) 456-7890" is converted to "(12-3) -4567" = Data error
"123 456-7890" is converted to "123- 45-6789" = Style error
"123 456.78.90" is converted to "123 456.78" = Data error

**Comment by zachleat** [comment]
Use the `data-politespace-strip` feature for this, included with v0.1.19 and documented on the readme.

A better alternative is to use formcore’s numeric-input https://github.com/filamentgroup/formcore#numeric-input which would allow you to maintain a strict maxlength, since it prevents non-numeric input.
